name: Testing
env:
  PROD_DB_USERNAME: root
  PROD_DB_PASSWORD:
  PROD_DB_NAME: gpa_testing
  PROD_DB_HOSTNAME: 127.0.0.1
  PORT: 3000
  JWT_SECRET_KEY_FMAP: test
on:
  [push]
  # pull_request:
  #   branches:
  #     - develop
  #     - master
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: ${{ env.PROD_DB_HOSTNAME }}
          MYSQL_DB: ${{ env.PROD_DB_NAME }}
          MYSQL_USER: ${{ env.PROD_DB_USERNAME }}
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"
    steps:
      # - uses: mirromutth/mysql-action@v1.1
      #   with:
      #     mysql database: ${{ env.PROD_DB_NAME }}
      #     mysql root password: ${{ env.PROD_DB_PASSWORD }}
      #     mysql user: ${{ env.PROD_DB_USERNAME }}
      #     mysql password: ${{ env.PROD_DB_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15
      - name: setup
        run: npm ci
      - name: setup jest
        run: npm i -g jest
      - name: test
        run: npm test
