name: Testing
env:
  PROD_DB_USERNAME: test
  PROD_DB_PASSWORD: test
  PROD_DB_NAME: gpa_testing
  PROD_DB_HOSTNAME: 127.0.0.1
  PORT: 3000
  JWT_SECRET_KEY_FMAP: test
on:
  [push]
  # pull_request:
  #   branches:
  #     - develop
  #     - master
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: node:14.5.0-alpine
      container_name: testing
    services:
      mysql-master:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_HOST: testing
          MYSQL_DATABASE: ${{ env.PROD_DB_NAME }}
          MYSQL_USER: ${{ env.PROD_DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.PROD_DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.PROD_DB_PASSWORD }}
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: npm ci
      - name: setup jest
        run: npm i -g jest
      - name: test
        run: npm test
